### ISSUE TITLE
java.io.IOException: Remote resource path [...] does not support range requests.

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1032]
# Task Description

The `org.carlspring.strongbox.testing.TestCaseWithMavenArtifactGenerationAndIndexing.assertStreamNotNull` causes the following exception to be thrown:

```
21:38:44.921 15-02-2019 | ERROR | kJoinPool-1-worker-1 | o.c.s.providers.repository.ProxyRepositoryProvider | Failed to resolve Path for proxied artifact [/java/opensource/carlspring/strongbox/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage-common-proxies/maven-central/org/apache/commons/commons-lang3/3.3/commons-lang3-3.3.jar]
java.io.IOException: Remote resource path [/java/opensource/carlspring/strongbox/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage-common-proxies/maven-central/org/apache/commons/commons-lang3/3.3/commons-lang3-3.3.jar] does not support range requests.
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryInputStream.retryReadIfPossible(ProxyRepositoryInputStream.java:185)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryInputStream.access$300(ProxyRepositoryInputStream.java:20)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryInputStream$ReadTemplate.doRead(ProxyRepositoryInputStream.java:148)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryInputStream.read(ProxyRepositoryInputStream.java:75)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2146)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
	at org.carlspring.strongbox.services.ArtifactManagementService.writeArtifact(ArtifactManagementService.java:189)
	at org.carlspring.strongbox.services.ArtifactManagementService.doStore(ArtifactManagementService.java:137)
	at org.carlspring.strongbox.services.ArtifactManagementService.store(ArtifactManagementService.java:120)
	at org.carlspring.strongbox.services.ArtifactManagementService$$FastClassBySpringCGLIB$$b290f309.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at org.carlspring.strongbox.data.tx.OEntityUnproxyAspect.transactional(OEntityUnproxyAspect.java:52)
	at sun.reflect.GeneratedMethodAccessor365.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.carlspring.strongbox.services.ArtifactManagementService$$EnhancerBySpringCGLIB$$76cdb6f0.store(<generated>)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.onSuccessfulProxyRepositoryResponse(ProxyRepositoryArtifactResolver.java:108)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.doFetch(ProxyRepositoryArtifactResolver.java:92)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.fetchRemoteResource(ProxyRepositoryArtifactResolver.java:75)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.resolvePathExclusive(ProxyRepositoryProvider.java:101)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.fetchPath(ProxyRepositoryProvider.java:73)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:231)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:43)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider$$FastClassBySpringCGLIB$$f2b828e0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider$$EnhancerBySpringCGLIB$$50ef29f1.fetchPath(<generated>)
	at org.carlspring.strongbox.services.impl.ArtifactResolutionServiceImpl.resolvePath(ArtifactResolutionServiceImpl.java:98)
	at org.carlspring.strongbox.testing.TestCaseWithMavenArtifactGenerationAndIndexing.assertStreamNotNull(TestCaseWithMavenArtifactGenerationAndIndexing.java:427)
	at org.carlspring.strongbox.providers.repository.RetryDownloadArtifactWithUnsupportedRangeRequestTest.lambda$unsupportedRangeProxyRepositoryRequestShouldSkipRetryFeature$0(RetryDownloadArtifactWithUnsupportedRangeRequestTest.java:62)
	at org.junit.jupiter.api.AssertThrows$ResultAwareThrowingSupplierAdapter.get(AssertThrows.java:133)
	at org.junit.jupiter.api.AssertThrows$ResultAwareThrowingSupplierAdapter.get(AssertThrows.java:123)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:80)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:38)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:1178)
	at org.carlspring.strongbox.providers.repository.RetryDownloadArtifactWithUnsupportedRangeRequestTest.unsupportedRangeProxyRepositoryRequestShouldSkipRetryFeature(RetryDownloadArtifactWithUnsupportedRangeRequestTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:114)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.joinConcurrentTasksInReverseOrderToEnableWorkStealing(ForkJoinPoolHierarchicalTestExecutorService.java:147)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:121)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.io.IOException: Connection lost.
	at org.carlspring.strongbox.providers.repository.RetryDownloadArtifactWithUnsupportedRangeRequestTest$OneTimeBrokenArtifactInputStream.read(RetryDownloadArtifactWithUnsupportedRangeRequestTest.java:94)
	at java.io.InputStream.read(InputStream.java:170)
	at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher$RemoteArtifactInputStream.read(RemoteArtifactStreamFetcher.java:155)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryInputStream.lambda$read$2(ProxyRepositoryInputStream.java:75)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryInputStream$ReadTemplate.doRead(ProxyRepositoryInputStream.java:140)
	... 90 common frames omitted
```

If this is a real issue, we need to investigate it. If it's an expected exception, then we should use the respective JUnit methods to intercept this and keep it silent, as the output logs should not throw unnecessary exceptions, because these can be alarming and confusing when looking out build logs.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by LeifBrooks** [comment]
This looks like it is working as designed. The test is making sure that "does not support range requests." is in the exception message, but ProxyRepositoryProvider.resolvePathExclusive() is logging the error as well as throwing it.

**Comment by carlspring** [comment]
Thanks for double-checking, @LeifBrooks (and sorry for the late reply) ! :)
