### ISSUE TITLE
org.carlspring.strongbox.artifact.ArtifactNotFoundException: null

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1034]
# Task Description

The `org.carlspring.strongbox.controllers.layout.maven.MavenArtifactControllerTest.testNonExistingArtifactDownload` causes the following exception to be thrown:

```
14:22:55.669 14-02-2019 | ERROR | kJoinPool-1-worker-1 | o.c.s.providers.repository.ProxyRepositoryProvider | Failed to resolve Path for proxied artifact [/home/jenkins/workspace/jenkins-strongbox-strongbox-master-2023-SGXT8nC/strongbox-web-core/target/strongbox-vault/storages/storage-common-proxies/maven-central/john/doe]
org.carlspring.strongbox.artifact.ArtifactNotFoundException: null
	at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.getConnection(RemoteArtifactStreamFetcher.java:70)
	at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.access$000(RemoteArtifactStreamFetcher.java:15)
	at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher$RemoteArtifactInputStream.getConnection(RemoteArtifactStreamFetcher.java:117)
	at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher$RemoteArtifactInputStream.getTarget(RemoteArtifactStreamFetcher.java:128)
	at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher$RemoteArtifactInputStream.available(RemoteArtifactStreamFetcher.java:167)
	at java.io.FilterInputStream.available(FilterInputStream.java:168)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryInputStream.available(ProxyRepositoryInputStream.java:94)
	at java.io.BufferedInputStream.available(BufferedInputStream.java:410)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.doFetch(ProxyRepositoryArtifactResolver.java:88)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.fetchRemoteResource(ProxyRepositoryArtifactResolver.java:75)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.resolvePathExclusive(ProxyRepositoryProvider.java:101)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.fetchPath(ProxyRepositoryProvider.java:73)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:231)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:43)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider$$FastClassBySpringCGLIB$$f2b828e0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider$$EnhancerBySpringCGLIB$$72184b3.fetchPath(<generated>)
	at org.carlspring.strongbox.services.impl.ArtifactResolutionServiceImpl.resolvePath(ArtifactResolutionServiceImpl.java:98)
	at org.carlspring.strongbox.controllers.layout.maven.MavenArtifactController.download(MavenArtifactController.java:112)
	at org.carlspring.strongbox.controllers.layout.maven.MavenArtifactController$$FastClassBySpringCGLIB$$760c4ba2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.carlspring.strongbox.controllers.layout.maven.MavenArtifactController$$EnhancerBySpringCGLIB$$1342010a.download(<generated>)
	at sun.reflect.GeneratedMethodAccessor523.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:166)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.carlspring.strongbox.security.authentication.StrongboxAuthenticationFilter.doFilterInternal(StrongboxAuthenticationFilter.java:63)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.carlspring.strongbox.security.authentication.CustomAnonymousAuthenticationFilter.doFilter(CustomAnonymousAuthenticationFilter.java:61)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:182)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.performRequest(MockMvcRequestSenderImpl.java:194)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.sendRequest(MockMvcRequestSenderImpl.java:430)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.get(MockMvcRequestSenderImpl.java:608)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.get(MockMvcRequestSenderImpl.java:76)
	at org.carlspring.strongbox.rest.client.RestAssuredArtifactClient.getResourceWithResponse(RestAssuredArtifactClient.java:276)
	at org.carlspring.strongbox.controllers.layout.maven.MavenArtifactControllerTest.testNonExistingArtifactDownload(MavenArtifactControllerTest.java:676)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:140)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:120)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:140)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:120)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
404
```

If this is a real issue, we need to investigate it. If it's an expected exception, then we should use the respective JUnit methods to intercept this and keep it silent, as the output logs should not throw unnecessary exceptions, because these can be alarming and confusing when looking out build logs.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by LeifBrooks** [comment]
I'll take this task

**Comment by carlspring** [comment]
Great! Thanks! :)

**Comment by LeifBrooks** [comment]
This exception is output from the logger in `ProxyRepositoryProvider.resolvePathExclusive(...)`
```
catch (IOException e) { 
    logger.error(String.format("Failed to resolve Path for proxied artifact [%s]", repositoryPath), e);
     throw e; 
}
```

Which is caught and swallowed in `ArtifactResolutionServiceImpl.resolvePath(...)`
```
try {
    return (RepositoryPath)repositoryProvider.fetchPath(repositoryPath);
} catch (ArtifactNotFoundException e) {
    return null;
}
```


Should we silence the logger output and let the clients of `ArtifactResolutionServiceImpl.resolvePath(...)` decide if they want to throw an exception based on the return value of null?

**Comment by LeifBrooks** [comment]
or just get rid of the stacktrace in the logger output?

**Comment by carlspring** [comment]
Does the artifact exist on the remote?

**Comment by LeifBrooks** [comment]
No. Its testing that the artifact isn't there. `testNonExistingArtifactDownload()`

**Comment by carlspring** [comment]
Well, in this case shouldn't the test be using JUnit's feature to expect that the exception is thrown?

**Comment by LeifBrooks** [comment]
I can do that, but as I said the exception is just being logged and then ignored, so there isn't an exception to be caught. We would have to pass it a long.

**Comment by carlspring** [comment]
Thanks for investing this one! It looks like it's by design and that there's no better way to silence it!

I will close this.
