### ISSUE TITLE
Investigate the com.hazelcast.transaction.TransactionException in the MavenProxyRepositoryProviderTestIT

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1086]
We need to investigate what has suddenly started to cause the `MavenProxyRepositoryProviderTestIT.whenDownloadingArtifactMetadataFileShouldBeMergedWhenExist`:

```
Error Message
Heuristic completion: outcome state is mixed; nested exception is org.springframework.transaction.TransactionSystemException: Could not commit Hazelcast transaction; nested exception is com.hazelcast.transaction.TransactionException: Transaction is timed-out!
Stacktrace
org.springframework.transaction.HeuristicCompletionException: Heuristic completion: outcome state is mixed; nested exception is org.springframework.transaction.TransactionSystemException: Could not commit Hazelcast transaction; nested exception is com.hazelcast.transaction.TransactionException: Transaction is timed-out!
	at org.carlspring.strongbox.providers.repository.MavenProxyRepositoryProviderTestIT.whenDownloadingArtifactMetadataFileShouldBeMergedWhenExist(MavenProxyRepositoryProviderTestIT.java:185)
Caused by: org.springframework.transaction.TransactionSystemException: Could not commit Hazelcast transaction; nested exception is com.hazelcast.transaction.TransactionException: Transaction is timed-out!
	at org.carlspring.strongbox.providers.repository.MavenProxyRepositoryProviderTestIT.whenDownloadingArtifactMetadataFileShouldBeMergedWhenExist(MavenProxyRepositoryProviderTestIT.java:185)
Caused by: com.hazelcast.transaction.TransactionException: Transaction is timed-out!
	at org.carlspring.strongbox.providers.repository.MavenProxyRepositoryProviderTestIT.whenDownloadingArtifactMetadataFileShouldBeMergedWhenExist(MavenProxyRepositoryProviderTestIT.java:185)
```

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by fuss86** [comment]
Fixed in #1092
