### ISSUE TITLE
Investigate the random test failures of the CronTaskControllerTest occurring under Windows

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1090]
# Task Description

We need to investigate these random test failures which seem to only be occurring under Windows.

# Error Message
```
Failed to deleteCronConfig job: 500 ==> expected: <200> but was: <500>
Stacktrace
org.opentest4j.AssertionFailedError: Failed to deleteCronConfig job: 500 ==> expected: <200> but was: <500>
	at org.carlspring.strongbox.controllers.cron.CronTaskControllerTest.deleteConfig(CronTaskControllerTest.java:314)
	at org.carlspring.strongbox.controllers.cron.CronTaskControllerTest.testGroovyCronTaskConfiguration(CronTaskControllerTest.java:175)
```

# Standard Output
```
04:30:35.287 01-03-2019 | INFO  | kJoinPool-1-worker-1 | o.c.s.users.userdetails.XmlUserDetailService       | Authorise under org.carlspring.strongbox.users.userdetails.StrongboxUserDetails@6d5af9bb
200
Content-Type: application/json;charset=UTF-8
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY

{
  "message" : "The configuration was saved successfully."
}
200
Content-Type: application/xml
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cron-tasks-configuration>
    <cron-task-configuration>
        <uuid>463ff872-b7b2-4cb9-aff9-37b3baed4f14</uuid>
        <name>Clear Each Repository's Trash Cron Job</name>
        <properties>
            <cronExpression>0 0 1 * * ?</cronExpression>
            <jobClass>org.carlspring.strongbox.cron.jobs.ClearRepositoryTrashCronJob</jobClass>
        </properties>
        <one-time-execution>false</one-time-execution>
        <immediate-execution>false</immediate-execution>
    </cron-task-configuration>
    <cron-task-configuration>
        <uuid>9dd9a6ef-d953-4ce0-be3d-3031fcfd993b</uuid>
        <name>Re-generate Artifacts Checksums Cron Job</name>
        <properties>
            <cronExpression>0 0 1 * * ?</cronExpression>
            <jobClass>org.carlspring.strongbox.cron.jobs.RegenerateChecksumCronJob</jobClass>
        </properties>
        <one-time-execution>false</one-time-execution>
        <immediate-execution>false</immediate-execution>
    </cron-task-configuration>
    <cron-task-configuration>
        <uuid>6d62a2b0-cc4b-4f61-a49e-f4e6d58a9810</uuid>
        <name>Remote index download for storage-common-proxies:carlspring</name>
        <properties>
            <cronExpression>0 0 5 * * ?</cronExpression>
            <jobClass>org.carlspring.strongbox.cron.jobs.DownloadRemoteMavenIndexCronJob</jobClass>
            <repositoryId>carlspring</repositoryId>
            <storageId>storage-common-proxies</storageId>
        </properties>
        <one-time-execution>false</one-time-execution>
        <immediate-execution>false</immediate-execution>
    </cron-task-configuration>
    <cron-task-configuration>
        <uuid>b44164a5-c900-43ff-8d13-7a0d0e509d1d</uuid>
        <name>Re-build All Maven Repositories Metadata Files Cron Job</name>
        <properties>
            <cronExpression>0 0 1 * * ?</cronExpression>
            <jobClass>org.carlspring.strongbox.cron.jobs.RebuildMavenMetadataCronJob</jobClass>
        </properties>
        <one-time-execution>false</one-time-execution>
        <immediate-execution>false</immediate-execution>
    </cron-task-configuration>
    <cron-task-configuration>
        <uuid>c9e7eeef-4e97-4500-aa12-e714a246c2dc</uuid>
        <name>Remove Timestamped Maven Snapshots Cron Job</name>
        <properties>
            <cronExpression>0 0 1 * * ?</cronExpression>
            <jobClass>org.carlspring.strongbox.cron.jobs.RemoveTimestampedMavenSnapshotCronJob</jobClass>
        </properties>
        <one-time-execution>false</one-time-execution>
        <immediate-execution>false</immediate-execution>
    </cron-task-configuration>
    <cron-task-configuration>
        <uuid>d0c3fc57-7c1e-4d19-8600-70cde5ac0f0e</uuid>
        <name>Fetch Remote Changes feed for storage-npm:npmjs</name>
        <properties>
            <cronExpression>0 0 * ? * * *</cronExpression>
            <jobClass>org.carlspring.strongbox.cron.jobs.FetchRemoteNpmChangesFeedCronJob</jobClass>
            <repositoryId>npmjs</repositoryId>
            <storageId>storage-npm</storageId>
        </properties>
        <one-time-execution>false</one-time-execution>
        <immediate-execution>true</immediate-execution>
    </cron-task-configuration>
    <cron-task-configuration>
        <uuid>8913a179-165f-4839-911c-9c1048f065f0</uuid>
        <name>Remote feed download for storage-common-proxies:nuget.org</name>
        <properties>
            <cronExpression>0 0 0 * * ?</cronExpression>
            <jobClass>org.carlspring.strongbox.cron.jobs.DownloadRemoteFeedCronJob</jobClass>
            <repositoryId>nuget.org</repositoryId>
            <storageId>storage-common-proxies</storageId>
        </properties>
        <one-time-execution>false</one-time-execution>
        <immediate-execution>true</immediate-execution>
    </cron-task-configuration>
    <cron-task-configuration>
        <uuid>e8427cf7-442d-467a-a9be-e9b4f762577f</uuid>
        <name>CRJG001</name>
        <properties>
            <cronExpression>0 11 11 11 11 ? 2100</cronExpression>
        </properties>
        <one-time-execution>true</one-time-execution>
        <immediate-execution>true</immediate-execution>
    </cron-task-configuration>
</cron-tasks-configuration>

200
Content-Type: application/json;charset=UTF-8
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY

{
  "message" : "The configuration was saved successfully."
}
200
Content-Type: application/json;charset=UTF-8
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY

{
  "uuid" : "e8427cf7-442d-467a-a9be-e9b4f762577f",
  "name" : "CRJG001",
  "properties" : {
    "elements" : [ "<?xml version=\"1.0\" encoding=\"UTF-16\"?>\n<cronExpression>0 11 11 11 11 ? 2100</cronExpression>" ]
  },
  "one-time-execution" : true,
  "immediate-execution" : true
}
04:30:35.401 01-03-2019 | INFO  | kJoinPool-1-worker-1 | o.c.strongbox.controllers.cron.CronTaskController  | >> CRON UUID: e8427cf7-442d-467a-a9be-e9b4f762577f
04:30:35.401 01-03-2019 | INFO  | kJoinPool-1-worker-1 | o.c.strongbox.controllers.cron.CronTaskController  | >> CRON NAME: CRJG001
04:30:35.401 01-03-2019 | INFO  | kJoinPool-1-worker-1 | o.c.strongbox.controllers.cron.CronTaskController  | >> Properties: {cronExpression=0 11 11 11 11 ? 2100}
200
Content-Type: application/json;charset=UTF-8
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY

{
  "message" : "The groovy script uploaded successfully."
}
04:30:35.442 01-03-2019 | ERROR | kJoinPool-1-worker-1 | o.c.strongbox.controllers.cron.CronTaskController  | Could not delete the configuration.
java.nio.file.FileSystemException: C:\jenkins\workspace\strongbox\strongbox-windows\strongbox-web-core\target\strongbox-vault\etc\conf\cron\groovy\GroovyTask.groovy: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at org.carlspring.strongbox.controllers.cron.CronTaskController.deleteConfiguration(CronTaskController.java:188)
	at org.carlspring.strongbox.controllers.cron.CronTaskController$$FastClassBySpringCGLIB$$8a5aabbf.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.carlspring.strongbox.controllers.cron.CronTaskController$$EnhancerBySpringCGLIB$$e71f4fc0.deleteConfiguration(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:930)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:166)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.carlspring.strongbox.security.authentication.StrongboxAuthenticationFilter.doFilterInternal(StrongboxAuthenticationFilter.java:63)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.carlspring.strongbox.security.authentication.CustomAnonymousAuthenticationFilter.doFilter(CustomAnonymousAuthenticationFilter.java:43)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:182)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.performRequest(MockMvcRequestSenderImpl.java:194)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.sendRequest(MockMvcRequestSenderImpl.java:430)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.delete(MockMvcRequestSenderImpl.java:632)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.delete(MockMvcRequestSenderImpl.java:76)
	at org.carlspring.strongbox.controllers.cron.CronTaskControllerTest.deleteCronConfig(CronTaskControllerTest.java:327)
	at org.carlspring.strongbox.controllers.cron.CronTaskControllerTest.deleteConfig(CronTaskControllerTest.java:312)
	at org.carlspring.strongbox.controllers.cron.CronTaskControllerTest.testGroovyCronTaskConfiguration(CronTaskControllerTest.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:140)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:120)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:140)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:120)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
500
Content-Type: application/json;charset=UTF-8
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY

{
  "message" : "Could not delete the configuration."
}
```

**Comment by carlspring** [comment]
Thanks, @fuss86! :-)

**Comment by carlspring** [comment]
@fuss86 : What is the status of this task?

**Comment by fuss86** [comment]
fixed
