### ISSUE TITLE
The MavenMetadataManagementControllerTest fails intermittently

### ISSUE THREAD

**Issue by prbobba** [strongbox/strongbox#1205]
# Bug Description

Observed issue:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M1:test (default-test) on project strongbox-web-core: There are test failures.
[ERROR]
[ERROR] Please refer to C:\work\strongbox\strongbox-web-core\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_181\jre\bin\java" -Xmx1024m -Xms512m -Dstrongbox.download.indexes.storage-common-proxies.*=false -Dstrongbox.download
.indexes.storage-springsource-proxies.*=false -Dstrongbox.download.indexes=false -Dstrongbox.download.indexes.storage-sbt-proxies.*=false -Dstrongbox.npm.remote.changes.enabled=false o
rg.apache.maven.surefire.booter.ForkedBooter C:\Users\pbobba\AppData\Local\Temp\surefire7795999347524093635 2019-04-13T14-19-10_710-jvmRun1 surefire3408736368709177612tmp surefire_0170
5599777429793636tmp"
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.carlspring.strongbox.controllers.layout.maven.MavenMetadataManagementControllerTest
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C ""C:\Program Files\Java\jdk1.8.0_181\jre\bin\java" -Xmx1024m -Xms512m -Dstrongbox.download.indexes.storage-common-proxies.*=false -Dstrongbox.download
.indexes.storage-springsource-proxies.*=false -Dstrongbox.download.indexes=false -Dstrongbox.download.indexes.storage-sbt-proxies.*=false -Dstrongbox.npm.remote.changes.enabled=false o
rg.apache.maven.surefire.booter.ForkedBooter C:\Users\pbobba\AppData\Local\Temp\surefire7795999347524093635 2019-04-13T14-19-10_710-jvmRun1 surefire3408736368709177612tmp surefire_0170
5599777429793636tmp"
[ERROR] Process Exit Code: 0
[ERROR] Crashed tests:
[ERROR] org.carlspring.strongbox.controllers.layout.maven.MavenMetadataManagementControllerTest
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:670)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:283)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:246)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1149)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:991)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:837)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

This test should be re-worked to use the new test annotations for creating test repositories and artifacts.

# Task Relationships

This task relates to #1165.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by carlspring** [comment]
@prbobba ,

Would you like to work on this? You will have to have a look at the tests that have already been fixed for #1165 and follow the same way of re-working the generation of their test repositories and artifacts using the new annotations that we have for this.

**Comment by rivalez** [comment]
@carlspring ,

I can pick this one.

**Comment by carlspring** [comment]
Hi @rivalez!

Feel free to do so and to join our [chat channel](https://chat.carlspring.org/) for more details and help! :)

**Comment by vikss** [comment]
@carlspring 
Can I take this?

**Comment by carlspring** [comment]
Hi @vikss ,

Sure, if you can reproduce and fix it, that'll be great! :)

**Comment by vikss** [comment]
@prbobba 
This command - "mvn install -Dintegration.tests -l output.log" - returned success with no failed/crashed test cases inside the strongbox-web-core folder.
Can you help me reproduce this issue?

**Comment by carlspring** [comment]
@vikss : 
What's your `mvn --version` output?

**Comment by vikss** [comment]
mvn --version 
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T00:03:14+05:30)
Maven home: /opt/apache-maven-3.5.4
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-148-generic", arch: "i386", family: "unix"

**Comment by vikss** [comment]
@carlspring 
Nevertheless, I have made the necessary changes. Could you please verify my pull request?

**Comment by vikss** [comment]
@carlspring 
You can close this one out.

**Comment by carlspring** [comment]
This is still using things like `createTimestampedSnapshotArtifact(,,,)`. We have annotations for this in place, right @ptirador? I think this still requires some more work.

@ptirador : Would you like to look into this?

**Comment by ptirador** [comment]
Sure! Let me look at it.

**Comment by carlspring** [comment]
Thanks a lot, @ptirador !

**Comment by ptirador** [comment]
@carlspring: This PR can be closed, as it was already solved in PR https://github.com/strongbox/strongbox/pull/1434.

**Comment by carlspring** [comment]
Thanks for letting me know!
