### ISSUE TITLE
NPE is showing while building the code

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#1532]
# Bug Description

While building Strongbox, a NPE is being thrown sometimes at random tests. This is probably a concurrency issue which doesn't seem to be directly affecting any of the tests (i.e. they are not failing) but the exception is getting thrown nonetheless.

# Steps To Reproduce

1. Clone Strongbox
2. `mvn clean install -Dintegration.tests` (but it's happening randomly so it might take a few attempts)

# Expected Behavior

No NPE in the console.

# Environment

* Strongbox Version: 148d597 (and earlier; you can also use the `master` branch)
* OS: Linux (probably Windows as well)
* Maven version (please provide the full output of `mvn --version`):
   ```
   Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T18:06:16+03:00)
   Maven home: /data/java/apache-maven-3.6.2
   Java version: 1.8.0_131, vendor: Oracle Corporation, runtime: /data/java/jdk1.8.0_131/jre
   Default locale: en_US, platform encoding: UTF-8
   OS name: "linux", version: "5.3.0-18-generic", arch: "amd64", family: "unix"
   ```

# Additional context 

```
[INFO] Running org.carlspring.strongbox.services.ArtifactMetadataServiceSnapshotsTest
Exception in thread "Thread-402" java.lang.NullPointerException
        at org.carlspring.strongbox.testing.storage.repository.RepositoryManagementTestExecutionListener$TestRepositoryProxyInvocationHandler.invoke(RepositoryManagementTestExecutionListener.java:77)
        at com.sun.proxy.$Proxy152.getLayout(Unknown Source)
        at org.carlspring.strongbox.providers.io.RepositoryFileSystemRegistry.lookupRepositoryFileSystemFactory(RepositoryFileSystemRegistry.java:47)
        at org.carlspring.strongbox.providers.io.RepositoryPathResolver.resolve(RepositoryPathResolver.java:36)
        at org.carlspring.strongbox.storage.indexing.AbstractRepositoryIndexDirectoryPathResolver.resolve(AbstractRepositoryIndexDirectoryPathResolver.java:24)
        at org.carlspring.strongbox.storage.indexing.AbstractRepositoryIndexCreator.apply(AbstractRepositoryIndexCreator.java:31)
        at org.carlspring.strongbox.storage.indexing.AbstractRepositoryIndexCreator.apply(AbstractRepositoryIndexCreator.java:18)
        at org.carlspring.strongbox.storage.indexing.local.RepositoryHostedIndexCreatorTest$PackedRepositoryIndexGeneratorThread.run(RepositoryHostedIndexCreatorTest.java:160)
Exception in thread "Thread-403" java.lang.NullPointerException
        at org.carlspring.strongbox.testing.storage.repository.RepositoryManagementTestExecutionListener$TestRepositoryProxyInvocationHandler.invoke(RepositoryManagementTestExecutionListener.java:77)
        at com.sun.proxy.$Proxy152.getLayout(Unknown Source)
        at org.carlspring.strongbox.providers.io.RepositoryFileSystemRegistry.lookupRepositoryFileSystemFactory(RepositoryFileSystemRegistry.java:47)
        at org.carlspring.strongbox.providers.io.RepositoryPathResolver.resolve(RepositoryPathResolver.java:36)
        at org.carlspring.strongbox.storage.indexing.AbstractRepositoryIndexDirectoryPathResolver.resolve(AbstractRepositoryIndexDirectoryPathResolver.java:24)
        at org.carlspring.strongbox.storage.indexing.AbstractRepositoryIndexCreator.apply(AbstractRepositoryIndexCreator.java:31)
        at org.carlspring.strongbox.storage.indexing.AbstractRepositoryIndexCreator.apply(AbstractRepositoryIndexCreator.java:18)
        at org.carlspring.strongbox.storage.indexing.local.RepositoryHostedIndexCreatorTest$PackedRepositoryIndexGeneratorThread.run(RepositoryHostedIndexCreatorTest.java:160)
Exception in thread "Thread-404" java.lang.NullPointerException
        at org.carlspring.strongbox.testing.storage.repository.RepositoryManagementTestExecutionListener$TestRepositoryProxyInvocationHandler.invoke(RepositoryManagementTestExecutionListener.java:77)
        at com.sun.proxy.$Proxy152.getLayout(Unknown Source)
        at org.carlspring.strongbox.providers.io.RepositoryFileSystemRegistry.lookupRepositoryFileSystemFactory(RepositoryFileSystemRegistry.java:47)
        at org.carlspring.strongbox.providers.io.RepositoryPathResolver.resolve(RepositoryPathResolver.java:36)
        at org.carlspring.strongbox.storage.indexing.AbstractRepositoryIndexDirectoryPathResolver.resolve(AbstractRepositoryIndexDirectoryPathResolver.java:24)
        at org.carlspring.strongbox.storage.indexing.AbstractRepositoryIndexCreator.apply(AbstractRepositoryIndexCreator.java:31)
        at org.carlspring.strongbox.storage.indexing.AbstractRepositoryIndexCreator.apply(AbstractRepositoryIndexCreator.java:18)
        at org.carlspring.strongbox.storage.indexing.local.RepositoryHostedIndexCreatorTest$PackedRepositoryIndexGeneratorThread.run(RepositoryHostedIndexCreatorTest.java:160)
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.407 s - in org.carlspring.strongbox.storage.indexing.local.RepositoryHostedIndexCreatorTest
```

**Comment by juniorrhis** [comment]
Working on it

**Comment by carlspring** [comment]
Thanks for picking it up! Feel free to join our [chat channel](https://chat.carlspring.org/)! :)

**Comment by anki2189** [comment]
@carlspring @cbrianhill @ptirador I tried to debug this issue below are my findings so far:

- When Test RepositoryHostedIndexCreatorTest#packedRepositoryIndexGeneratorShouldBeThreadSafe is executed TestRepositoryManagementContextSupport#beforeTestExecution callback is invoked before its execution which populates Context in ThreadLocal variable in class **TestRepositoryManagementApplicationContext**

- Now as packedRepositoryIndexGeneratorShouldBeThreadSafe spawn 3 new threads in its test method which tries to get Context from the same ThreadLocal variable populated in above point,
these thread get its value as null as it was create by their parent thread and hence NullPointer is thrown in RepositoryManagementTestExecutionListener#TestRepositoryProxyInvocationHandler class.

- One possible solution to fix this issue could be explicitly populate Context for these threads before execution of task assigned to these threads and clear the Context one task is over.

@cbrianhill @ptirador @carlspring Any other thoughts?

**Comment by fuss86** [comment]
Hi @anki2189 :)

Great hunt, great investigation ! 

I think we should try with [InheritableThreadLocal](https://docs.oracle.com/javase/8/docs/api/java/lang/InheritableThreadLocal.html). 

@sbespalov , what do you think ?

**Comment by anki2189** [comment]
@sbespalov @fuss86 Should I go ahead with InheritableThreadLocal or the solution which I proposed above?

**Comment by sbespalov** [comment]
@anki2189 thanks for the excellent analysis. If I understand correclty we can get the `TestRepositoryManagementContext` instance within the `TestRepositoryProxyInvocationHandler` constructor and then use this instance when`TestRepositoryProxyInvocationHandler#invoke` method called with no matter of caller thread.

**Comment by sbespalov** [comment]
we should also apply this for `ArtifactManagementTestExecutionListener.TestArtifactProxyInvocationHandler` and `ArtifactManagementTestExecutionListener.ListInvocationHandler`.

**Comment by steve-todorov** [comment]
Awesome work! Thanks for fixing this @anki2189 ! :)
