### ISSUE TITLE
Investigate occasionally failing MavenMetadataExpirationSingleGroupCaseTest test

### ISSUE THREAD

**Issue by fuss86** [strongbox/strongbox#1553]
# Bug Description

We sometimes encounter problems with the following test `MavenMetadataExpirationSingleGroupCaseTest.groupRepositoryVersionLevelMetadataShouldBeRefreshedAsItsSingleProxySubrepository`. Below is the error from `CI`. We should find out what is the reason of failing test and fix it.

```
Error
Expecting:
 <"b26dcfc429fe3f615fe3411e2951badf2d5883a4">
to be equal to:
 <"ff1c6bf8466916b0429d9b31e3ed7834486aafc0">
but was not.
Stacktrace
org.opentest4j.AssertionFailedError: 
Expecting:
 <"b26dcfc429fe3f615fe3411e2951badf2d5883a4">
to be equal to:
 <"ff1c6bf8466916b0429d9b31e3ed7834486aafc0">
but was not.
	at org.carlspring.strongbox.providers.io.MavenMetadataExpirationSingleGroupCaseTest.groupRepositoryVersionLevelMetadataShouldBeRefreshedAsItsSingleProxySubrepository(MavenMetadataExpirationSingleGroupCaseTest.java:129)
```

Problem might be related with `MavenMetadataExpirationProxyCaseTest` and the thing that we run tests concurrently. See below logs from `CI`

```
[INFO] Running org.carlspring.strongbox.providers.io.MavenMetadataExpirationSingleGroupCaseTest
[INFO] Running org.carlspring.strongbox.providers.io.MavenArtifactTest
[INFO] Running org.carlspring.strongbox.providers.io.MavenMetadataExpirationProxyCaseTest
[INFO] Running org.carlspring.strongbox.providers.repository.MavenGroupRepositoryProviderTest
19:29:09.223 20-10-2019 | DEBUG | kJoinPool-1-worker-3 | l.servicelocator.CustomResolverServiceLocator      | ServiceLocator.findClasses for liquibase.parser.NamespaceDetails
19:29:09.223 20-10-2019 | DEBUG | kJoinPool-1-worker-3 | l.servicelocator.CustomResolverServiceLocator      | ServiceLocator finding classes matching interface liquibase.parser.NamespaceDetails
19:29:09.224 20-10-2019 | DEBUG | kJoinPool-1-worker-3 | l.servicelocator.CustomResolverServiceLocator      | liquibase.parser.core.xml.StandardNamespaceDetails matches liquibase.parser.NamespaceDetails
19:29:09.224 20-10-2019 | DEBUG | kJoinPool-1-worker-3 | l.i.spring.SpringLiquibase$SpringResourceOpener    | Opening jar:file:/cache/strongbox-builds-strongbox-PR-954/.m2/os-linux/org/liquibase/liquibase-core/3.6.3/liquibase-core-3.6.3.jar!/liquibase/parser/core/xml/dbchangelog-3.2.xsd as liquibase/parser/core/xml/dbchangelog-3.2.xsd
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.285 s <<< FAILURE! - in org.carlspring.strongbox.providers.io.MavenMetadataExpirationProxyCaseTest
[ERROR] expiredProxyRepositoryMetadataPathShouldBeRefetched{Repository, Repository, Repository}  Time elapsed: 0.285 s  <<< ERROR!
java.lang.NullPointerException
	at org.carlspring.strongbox.providers.io.MavenMetadataExpirationProxyCaseTest.expiredProxyRepositoryMetadataPathShouldBeRefetched(MavenMetadataExpirationProxyCaseTest.java:89)

[INFO] Running org.carlspring.strongbox.providers.layout.Maven2LayoutProviderTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.082 s - in org.carlspring.strongbox.providers.io.MavenArtifactTest
[INFO] Running org.carlspring.strongbox.providers.repository.RetryDownloadArtifactWithUnsupportedRangeRequestTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in org.carlspring.strongbox.providers.io.MavenMetadataExpirationSingleGroupCaseTest
[ERROR] groupRepositoryVersionLevelMetadataShouldBeRefreshedAsItsSingleProxySubrepository{Repository, Repository, Repository, Repository}  Time elapsed: 0.004 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

Expecting:
 <"b26dcfc429fe3f615fe3411e2951badf2d5883a4">
to be equal to:
 <"ff1c6bf8466916b0429d9b31e3ed7834486aafc0">
but was not.
	at org.carlspring.strongbox.providers.io.MavenMetadataExpirationSingleGroupCaseTest.groupRepositoryVersionLevelMetadataShouldBeRefreshedAsItsSingleProxySubrepository(MavenMetadataExpirationSingleGroupCaseTest.java:129)

[INFO] Running org.carlspring.strongbox.providers.repository.RetryDownloadArtifactWithSingleFailureAtSomePointTest
19:29:09.543 20-10-2019 | DEBUG | kJoinPool-1-worker-3 | l.i.spring.SpringLiquibase$SpringResourceOpener    | Opening jar:file:/cache/strongbox-builds-strongbox-PR-954/.m2/os-linux/org/carlspring/strongbox/strongbox-db-liquibase/1.0-SNAPSHOT/strongbox-db-liquibase-1.0-SNAPSHOT.jar!/db/changelog/v1.0.0/db.changelog-1.0.0.xml as classpath:/db/changelog/v1.0.0/db.changelog-1.0.0.xml
```

# Steps To Reproduce

It is hard to reproduce this issue. It shows up from time to time in `CI` server. Investigator should focus on `strongbox-storage-maven-layout-provider` module tests run in parallel.

# Expected Behavior

These tests should always pass :)

# Useful Links

* CI failed build https://jenkins.carlspring.org/job/strongbox/job/builds/job/strongbox/job/PR-954/101/

**Comment by mukuldhariwal94** [comment]
is this up for grabs?

**Comment by carlspring** [comment]
Hi,
Yes, please , feel free to dig in!

**Comment by anki2189** [comment]
@fuss86 This issue should be fixed after https://github.com/strongbox/strongbox/pull/1601. What are your thoughts?

**Comment by fuss86** [comment]
@anki2189 I don't think it's related, we are not spawning any additional Thread in `MavenMetadataExpirationProxyCaseTest#expiredProxyRepositoryMetadataPathShouldBeRefetchedRegardlessOfChecksum`. Maybe I'm missing something , please correct me or show me your doubts :)

Thanks :)

**Comment by navkumar258** [comment]
I am looking for my first contribution, is the issue still open or is someone working on it?

**Comment by carlspring** [comment]
Hi,

If you can reproduce and fix it, that would be great! It might however be obsolete, if you can't. Give it a go and report back any findings. Thanks!

Also, feel free to join our [chat channel](https://chat.carlspring.org/).

**Comment by navkumar258** [comment]
@carlspring didn't mean to bother you...is the build passing?....my build is failing at web-core module due to an org.json package symbol not found error in the JWTAuthenticationController class....please help.

**Comment by carlspring** [comment]
Yes, the build is passing. We have a chat channel for build help. Have you followed the [Getting Started](https://strongbox.github.io/developer-guide/getting-started.html) and [Building The Code](https://strongbox.github.io/developer-guide/building-the-code.html) sections in our "Developer's Guide"?

**Comment by navkumar258** [comment]
@carlspring yes...i followed the link...able to build other modules but it gives compilation error when building the above mentioned module.Below is the error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project strongbox-web-core: Compilation failure
[ERROR] /D:/nk00427541/GitHub_Contribs/strongbox/strongbox/strongbox-web-core/src/test/java/org/carlspring/strongbox/controllers/JwtAuthenticationTest.java:[16,16] cannot find symbol
[ERROR]   symbol:   class JSONObject
[ERROR]   location: package org.json`

**Comment by carlspring** [comment]
As I said, please use our chat channel for build issues.

**Comment by mehtakaran9** [comment]
@carlspring I would like to take a crack at this, can I try this out?

**Comment by carlspring** [comment]
Hi @mehtakaran9 ,

Thanks for offering to help! Feel free to try and reproduce it and report back your findings! Please, let use know either way! :)
