### ISSUE TITLE
Clean up temporary file after ArtifactOperationsValidatorTest run

### ISSUE THREAD

**Issue by sainalshah** [strongbox/strongbox#1616]
# Bug Description

Integration test fails when run without maven clean goal.

# Steps To Reproduce

1. Build and run integration tests with mvn install clean -DintegrationTests (or without clean goal)
2. Run integration tests with command mvn install -DintegrationTests

# Expected Behavior
Integration test result should be success.

# Environment

* Strongbox Version: 
* OS: Ubuntu/ Linux
* Maven version (please provide the full output of `mvn --version`): 
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_162, vendor: Oracle Corporation, runtime: /opt/jvm/jdk1.8.0_162/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-36-generic", arch: "amd64", family: "unix"

# Additional context 

Throws exception 

```
java.nio.file.FileAlreadyExistsException: /home/Projects/strongbox/strongbox-storage/strongbox-storage-api/target/strongbox-vault/storages/storage0/releases/validate-test.jar

	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at org.carlspring.strongbox.storage.validation.resource.ArtifactOperationsValidatorTest.checkArtifactSizeTest(ArtifactOperationsValidatorTest.java:123)
```
# Proposed Solution 
Clean up the temporary file after test run.

**Comment by carlspring** [comment]
Thanks, @sainalshah ! :)
