### ISSUE TITLE
Nuget.org default proxy fetch remote cron job failing

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [strongbox/strongbox#1640]
# Bug Description

Running a fresh/wiped instance of the strongbox, the nuget.org proxy cron job fails with `Illegal artifact path [测试更新包/1.0.0/测试更新包.1.0.0.nupkg` as shown in `strongbox-download-remote-feed-cron-job.log` 

Looks like the parsing of the package name fails and then fails the download.

<details><summary>traceback from strongbox-download-remote-feed-cron-job.log</summary><p>

---

```
17:56:30.457 11-01-2020 | INFO  | pool-6-thread-5      | o.c.strongbox.cron.jobs.DownloadRemoteFeedCronJob  | Cron job [Remote feed download for storage-common-proxies:nuget.org] enabled, executing.
17:59:32.549 11-01-2020 | ERROR | pool-6-thread-5      | o.c.strongbox.cron.jobs.DownloadRemoteFeedCronJob  | Failed to execute cron job task [Remote feed download for storage-common-proxies:nuget.org].
java.lang.IllegalArgumentException: Illegal artifact path [测试更新包/1.0.0/测试更新包.1.0.0.nupkg].
	at org.springframework.util.Assert.isTrue(Assert.java:118)
	at org.carlspring.strongbox.artifact.coordinates.NugetArtifactCoordinates.parse(NugetArtifactCoordinates.java:157)
	at org.carlspring.strongbox.providers.layout.NugetLayoutProvider.getArtifactCoordinates(NugetLayoutProvider.java:62)
	at org.carlspring.strongbox.providers.layout.NugetLayoutProvider.getArtifactCoordinates(NugetLayoutProvider.java:36)
	at org.carlspring.strongbox.providers.layout.AbstractLayoutProvider.getRepositoryFileAttributes(AbstractLayoutProvider.java:158)
	at org.carlspring.strongbox.providers.layout.LayoutFileSystemProvider.getRepositoryFileAttributes(LayoutFileSystemProvider.java:348)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider.readAttributes(StorageFileSystemProvider.java:567)
	at java.nio.file.Files.readAttributes(Files.java:1964)
	at java.nio.file.Files.getAttribute(Files.java:1869)
	at org.carlspring.strongbox.providers.io.RepositoryFiles.readCoordinates(RepositoryFiles.java:78)
	at org.carlspring.strongbox.repository.NugetRepositoryFeatures.parseFeed(NugetRepositoryFeatures.java:242)
	at org.carlspring.strongbox.repository.NugetRepositoryFeatures.downloadRemoteFeed(NugetRepositoryFeatures.java:193)
	at org.carlspring.strongbox.repository.NugetRepositoryFeatures.downloadRemoteFeed(NugetRepositoryFeatures.java:133)
	at org.carlspring.strongbox.repository.NugetRepositoryFeatures.downloadRemoteFeed(NugetRepositoryFeatures.java:117)
	at org.carlspring.strongbox.cron.jobs.DownloadRemoteFeedCronJob.executeTask(DownloadRemoteFeedCronJob.java:40)
	at org.carlspring.strongbox.cron.jobs.AbstractCronJob.executeInternal(AbstractCronJob.java:85)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
</p></details>

# Steps To Reproduce

1. Start a new instance of strongbox with default/initial config
2. Wait a couple of minutes for the cron job to fail

# Expected Behavior

Cron job completes without error

# Environment

* Strongbox Version: 1.0-SNAPSHOT revision 8c90fd863ca1384c
* OS: Debian 10
* Maven version:
```

Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_232, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.19.0-6-amd64", arch: "amd64", family: "unix"

```

**Comment by carlspring** [comment]
@anki2189 : Would you like to have a look at this one as well?

**Comment by anki2189** [comment]
@carlspring : Cron is working fine on my machine. From the logs what I am able to understand is 
`NUGET_PACKAGE_REGEXP` is not able to match String having chinese characters (`测试更新包/1.0.0/测试更新包.1.0.0.nupkg`)
