### ISSUE TITLE
Fix the WhenRepositoryIsNotAliveDontCleanExpiredArtifactsTestIT

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1746]
# Task Description

We need to fix this test against the `issues/1649` branch.

Failed Jenkins build [here](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1676/112/tests)

# Task Relationships

This task:
* Is a sub-task of: #1649

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @sbespalov
  * @carlspring
  * @steve-todorov

**Comment by jillguardian** [comment]
Hello. I'd like to start contributing by writing and fixing tests. Is this still up for grabs? [I sent a message in the group chat, too.]

BTW, the linked build is blank for me. Is there anything I need to do? Thank you.

**Comment by carlspring** [comment]
Hi,

Thanks for offering to help! You would have to re-enable the test and run the build and track the bug.

**Comment by carlspring** [comment]
The linked build no longer exists in Jenkins, but you should be able to reproduce it locally when running all the tests with `mvn clean install -Dintegration.tests`.

**Comment by carlspring** [comment]
This has either already been solved by previous changes, or will be fixed with #1764 .

**Comment by jillguardian** [comment]
I'll pick up some other task then. Thank you.

**Comment by carlspring** [comment]
It seems that this is still failing. Feel free to dig into it.

**Comment by jillguardian** [comment]
Relevant logs from [failing test](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1764/5/tests/) in commit 9e7b8b0:

```
04:13:59.477 | E | 1-worker-3 | o.c.s.t.s.r.TestRepositoryContext     | Failed to close [TestRepository] with id [storage-common-proxies/maven-central-dead] 
java.nio.file.NoSuchFileException: /home/jenkins/agent/workspace/rongbox_builds_strongbox_PR-1764/linux/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage-common-proxies/maven-central-dead/org/carlspring/maven/maven-commons/1.2/maven-commons-1.2.jar.md5
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider.readAttributes(StorageFileSystemProvider.java:513)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.Files.walkFileTree(Files.java:2706)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider.recursiveDeleteExceptRoot(StorageFileSystemProvider.java:228)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider.delete(StorageFileSystemProvider.java:206)
	at org.carlspring.strongbox.providers.layout.LayoutFileSystemProvider.delete(LayoutFileSystemProvider.java:261)
	at org.carlspring.strongbox.providers.layout.Maven2FileSystemProvider.delete(Maven2FileSystemProvider.java:80)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider.delete(StorageFileSystemProvider.java:178)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.carlspring.strongbox.repository.AbstractRepositoryManagementStrategy.removeDirectoryStructure(AbstractRepositoryManagementStrategy.java:99)
	at org.carlspring.strongbox.repository.AbstractRepositoryManagementStrategy.removeRepository(AbstractRepositoryManagementStrategy.java:85)
	at org.carlspring.strongbox.services.impl.RepositoryManagementServiceImpl.removeRepository(RepositoryManagementServiceImpl.java:103)
	at org.carlspring.strongbox.testing.storage.repository.TestRepositoryContext.closeInternal(TestRepositoryContext.java:268)
	at org.carlspring.strongbox.testing.storage.repository.TestRepositoryContext.close(TestRepositoryContext.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

I can't reproduce the issue on my machine, but it seems like the issue is that the path to the repository is incorrect.

**Comment by sbespalov** [comment]
most likely it could be fixed same way as #1831
