### ISSUE TITLE
Fix failing HttpConnectionPoolConfigurationManagementControllerTest test under windows.

### ISSUE THREAD

**Issue by steve-todorov** [strongbox/strongbox#564]
It seems that #546 has introduced some failing test cases under windows. All of the tests in `org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest` are failing only on windows machines.

```
[INFO] Running org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest
21:58:23.482 02-02-2018 | DEBUG | main                 | onnectionPoolConfigurationManagementControllerTest | Initializing RestAssured...
21:58:23.493 02-02-2018 | DEBUG | main                 | onnectionPoolConfigurationManagementControllerTest | Initializing RestAssured...
21:58:23.495 02-02-2018 | DEBUG | main                 | onnectionPoolConfigurationManagementControllerTest | Initializing RestAssured...
21:58:23.497 02-02-2018 | DEBUG | main                 | onnectionPoolConfigurationManagementControllerTest | Initializing RestAssured...
21:58:23.499 02-02-2018 | DEBUG | main                 | onnectionPoolConfigurationManagementControllerTest | Initializing RestAssured...
21:58:23.500 02-02-2018 | DEBUG | main                 | onnectionPoolConfigurationManagementControllerTest | Initializing RestAssured...
[ERROR] Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 0.026 s <<< FAILURE! - in org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest
[ERROR] testSetAndGetNumberOfConnectionsForProxyRepositoryWithJsonAcceptHeader(org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest)  Time elapsed: 0.011 s  <<< ERROR!
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest.setUp(HttpConnectionPoolConfigurationManagementControllerTest.java:47)

[ERROR] testSetAndGetMaxNumberOfConnectionsForProxyRepositoryWithTextAcceptHeader(org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest)  Time elapsed: 0 s  <<< ERROR!
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest.setUp(HttpConnectionPoolConfigurationManagementControllerTest.java:47)

[ERROR] testSetAndGetDefaultNumberOfConnectionsForProxyRepositoryWithJsonAcceptHeader(org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest)  Time elapsed: 0 s  <<< ERROR!
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest.setUp(HttpConnectionPoolConfigurationManagementControllerTest.java:47)

[ERROR] testSetAndGetNumberOfConnectionsForProxyRepositoryWithTextAcceptHeader(org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest)  Time elapsed: 0.001 s  <<< ERROR!
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest.setUp(HttpConnectionPoolConfigurationManagementControllerTest.java:47)

[ERROR] testSetAndGetDefaultNumberOfConnectionsForProxyRepositoryWithTextAcceptHeader(org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest)  Time elapsed: 0.002 s  <<< ERROR!
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest.setUp(HttpConnectionPoolConfigurationManagementControllerTest.java:47)

[ERROR] testSetAndGetMaxNumberOfConnectionsForProxyRepositoryWithJsonAcceptHeader(org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest)  Time elapsed: 0.001 s  <<< ERROR!
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at org.carlspring.strongbox.controllers.HttpConnectionPoolConfigurationManagementControllerTest.setUp(HttpConnectionPoolConfigurationManagementControllerTest.java:47)

[INFO] Running org.carlspring.strongbox.controllers.maven.MavenArtifactControllerTest
21:58:23.666 02-02-2018 | DEBUG | main                 | o.c.s.users.userdetails.StrongboxUserDetailService | Loading user details for developer01 ...
```

**Comment by carlspring** [comment]
@steve-todorov , @fuss86 

Is this issue still relevant, or can it be close?

**Comment by steve-todorov** [comment]
I believe @fuss86 has resolved this in https://github.com/strongbox/strongbox/pull/581 ?

**Comment by fuss86** [comment]
Yes, it can be closed.
