### ISSUE TITLE
Fix failing Nuget integration tests

### ISSUE THREAD

**Issue by danielbrzn** [strongbox/strongbox#571]
Currently, Nuget integration tests are failing because the deletion of an artifact from the repository doesn't seem to be working, although it says that there is a successful deletion.

Log:
```
Execute command[s]:
C:\nuget.exe delete Org.Carlspring.Strongbox.Examples.Nuget.Mono 1.0.0 -Source http://localhost:48080/storages/storage-nuget/nuget-releases -NonInteractive -ConfigFile C:\Users\Daniel\Desktop\strongbox-web-integration-tests\target\nuget-it/NuGet.config
WARNING: Deleting Org.Carlspring.Strongbox.Examples.Nuget.Mono 1.0.0 from the 'http://localhost:48080/storages/storage-nuget/nuget-releases'.
  DELETE http://localhost:48080/storages/storage-nuget/nuget-releases/Org.Carlspring.Strongbox.Examples.Nuget.Mono/1.0.0
19:08:28.419 03-02-2018 | DEBUG | qtp147623131-68      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.carlspring.strongbox.security.vote.CustomAccessDecisionVoter@4edf1076, returned: 0
19:08:28.484 03-02-2018 | DEBUG | qtp147623131-68      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.carlspring.strongbox.security.vote.CustomPreInvocationAuthorizationAdviceVoter@3e6abc29, returned: 1
19:08:28.563 03-02-2018 | INFO  | qtp147623131-68      | o.c.s.controllers.nuget.NugetArtifactController    | Nuget delete request: storageId-[storage-nuget]; repositoryId-[nuget-releases]; packageId-[Org.Carlspring.Strongbox.Examples.Nuget.Mono]
19:08:28.563 03-02-2018 | DEBUG | qtp147623131-68      | o.c.s.providers.layout.AbstractLayoutProvider      | Checking in storage-nuget:nuget-releases(Org.Carlspring.Strongbox.Examples.Nuget.Mono/1.0.0/Org.Carlspring.Strongbox.Examples.Nuget.Mono.nuspec)...
19:08:28.635 03-02-2018 | DEBUG | qtp147623131-68      | o.c.s.event.artifact.ArtifactEventListenerRegistry | Dispatching ArtifactEventTypeEnum.EVENT_ARTIFACT_PATH_DELETED event for storage-nuget:nuget-releases/Org.Carlspring.Strongbox.Examples.Nuget.Mono/1.0.0/Org.Carlspring.Strongbox.Examples.Nuget.Mono.nuspec...
19:08:28.649 03-02-2018 | DEBUG | qtp147623131-68      | o.c.s.providers.layout.AbstractLayoutProvider      | Removed /nuget-releases/Org.Carlspring.Strongbox.Examples.Nuget.Mono/1.0.0/Org.Carlspring.Strongbox.Examples.Nuget.Mono.nuspec
  OK http://localhost:48080/storages/storage-nuget/nuget-releases/Org.Carlspring.Strongbox.Examples.Nuget.Mono/1.0.0 315ms
Org.Carlspring.Strongbox.Examples.Nuget.Mono 1.0.0 was deleted successfully.


Execute command[s]:
C:\nuget.exe list Org.Carlspring -ConfigFile C:\Users\Daniel\Desktop\strongbox-web-integration-tests\target\nuget-it/NuGet.config
19:08:29.441 03-02-2018 | DEBUG | qtp147623131-17      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.carlspring.strongbox.security.vote.CustomAccessDecisionVoter@4edf1076, returned: 0
19:08:29.443 03-02-2018 | DEBUG | qtp147623131-17      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.carlspring.strongbox.security.vote.CustomPreInvocationAuthorizationAdviceVoter@3e6abc29, returned: -1
19:08:29.444 03-02-2018 | DEBUG | qtp147623131-17      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.springframework.security.access.vote.RoleVoter@61cfbd77, returned: 0
19:08:29.445 03-02-2018 | DEBUG | qtp147623131-17      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.springframework.security.access.vote.AuthenticatedVoter@6352bee0, returned: 0
Using credentials from config. UserName: admin
19:08:29.469 03-02-2018 | DEBUG | qtp147623131-66      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.carlspring.strongbox.security.vote.CustomAccessDecisionVoter@4edf1076, returned: 0
19:08:29.485 03-02-2018 | DEBUG | qtp147623131-66      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.carlspring.strongbox.security.vote.CustomPreInvocationAuthorizationAdviceVoter@3e6abc29, returned: -1
19:08:29.485 03-02-2018 | DEBUG | qtp147623131-66      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.springframework.security.access.vote.RoleVoter@61cfbd77, returned: 0
19:08:29.494 03-02-2018 | DEBUG | qtp147623131-66      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.springframework.security.access.vote.AuthenticatedVoter@6352bee0, returned: 0
19:08:29.677 03-02-2018 | DEBUG | qtp147623131-20      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.carlspring.strongbox.security.vote.CustomAccessDecisionVoter@4edf1076, returned: 0
19:08:29.681 03-02-2018 | DEBUG | qtp147623131-20      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.carlspring.strongbox.security.vote.CustomPreInvocationAuthorizationAdviceVoter@3e6abc29, returned: 1
19:08:29.833 03-02-2018 | DEBUG | qtp147623131-66      | o.c.strongbox.services.ArtifactEntryService        | Executing SQL query> SELECT * FROM ArtifactEntry WHERE artifactCoordinates.coordinates.extension.toLowerCase() like :extension AND artifactCoordinates.coordinates.id.toLowerCase() like :id AND (storageId = :storageId0 AND repositoryId = :repo
sitoryId0) AND tagSet contains (name = :lastversionTag) ORDER BY artifactCoordinates.uuid LIMIT 1000
19:08:29.845 03-02-2018 | DEBUG | qtp147623131-66      | o.c.s.controllers.nuget.NugetArtifactController    | Got 1 packages
19:08:29.846 03-02-2018 | DEBUG | qtp147623131-66      | o.c.s.controllers.nuget.NugetArtifactController    | Prepared 1 packages
Org.Carlspring.Strongbox.Examples.Nuget.Mono 1.0.0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 54.181 s
[INFO] Finished at: 2018-02-03T19:08:30+08:00
[INFO] Final Memory: 91M/1556M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.5:execute (nuget-integration-tests) on project strongbox-web-integration-tests: Error occurred while calling a method on a Groovy class from classpath.: InvocationTargetException: assert !output.contains("Org.Carlspring.Strongbox.Examples.Nuget.Mono")
[ERROR]        ||      |
[ERROR]        ||      true
[ERROR]        |Using credentials from config. UserName: admin
[ERROR]        |Org.Carlspring.Strongbox.Examples.Nuget.Mono 1.0.0
[ERROR]        false
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

@sbespalov

**Comment by carlspring** [comment]
@danielbrzn ,

Thanks for reporting this!

@sbespalov ,

Could you have a look, when you get a chance, please? Thanks! :)

**Comment by sbespalov** [comment]
it seems that this is some sort of regress. 
Maybe @gokhankuyucak will be interesting to dig into our Nuget stuff and fix it?

**Comment by sbespalov** [comment]
@carlspring

**Comment by carlspring** [comment]
@sbespalov,

Well, if @gokhankuyucak could look into it, that would be great! It would give him a chance to get acquainted with how things works in terms of the code. :)

@gokhankuyucak,

This is how to test it:
```
mvn clean install -P!run-maven-it-tests,run-nuget-it-tests
```

**Comment by gokhankuyucak** [comment]
@sbespalov, @carlspring 
As I checked, nuget list function gets the results from database, but nuget delete function deletes  only the nuspec file from folder. So I think we need to delete both from db and folder. 

In code, we need to pass parameters "version" and "packageId" to **ArtifactManagementService**.delete method in **NugetArtifactController**.deletePackage method. 

 

- **NugetArtifactController**.deletePackage:
  `getArtifactManagementService().delete(storageId, repositoryId, path, true);`
needs to be 
 `getArtifactManagementService().delete(storageId, repositoryId, path,packageId,version true);`

- **ArtifactManagementService**.delete:
insert following lines after line 402:
```
//Search the artifacts from db with packageid and version filter
Map<String,String> coordinates = new HashMap<String,String>();
        coordinates.put("id",packageId);
        coordinates.put("version",version);
        List <ArtifactEntry> artifactEntryList = artifactEntryService.findArtifactList(storageId,repositoryId,coordinates,true);
```
        
insert following line after `layoutProvider.delete(storageId, repositoryId, artifactPath, force);`
`artifactEntryService.delete(artifactEntryList); // Deletes from db`

My question is, **ArtifactManagementService**.delete method is used by maven too, and if I update **ArtifactManagementService**.delete parameter size, I need to update usages too. 
On the other hand we can change the event of nuget list method, instead of seeking in db we can use nuspec search in folders. Which one is a better way? Do you have any other options?

**Comment by sbespalov** [comment]
@gokhankuyucak you can find ArtefactEntry with parameters you have there using method below:
```
ArtifactEntryService.findOneArtifact(String storageId, String repositoryId, String path)
```
and then you can delete it with:
```
ArtifactEntryService.delete(entity)
```

**Comment by gokhankuyucak** [comment]
Created PR #593

**Comment by carlspring** [comment]
@danielbrzn ,

I've merged @gokhankuyucak 's PR for this. Would you like to give it another go, just in case?

**Comment by danielbrzn** [comment]
Seems to have fixed the problem. However there's an issue with the `test-install-with-transitive-deps` script. Log as shown below.

```
  PUT http://localhost:48080/storages/storage-nuget/nuget-releases/
21:18:18.618 10-02-2018 | DEBUG | qtp147623131-64      | o.s.web.filter.CommonsRequestLoggingFilter         | Before request [uri=/storages/storage-nuget/nuget-releases/;client=0:0:0:0:0:0:0:1;headers={Expect=[100-continue], X-NuGet-ApiKey=[eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTdHJvbmdib3giLCJqdGkiOiJNVWx4dUdyME5DU003bXNnWTVocUtnIiwic3ViIjoiYWRtaW4iLCJzZWN1cml0eS10b2tlbi1rZXkiOiJhZG1pbi1zZWNyZXQifQ.8tIKijVBv2apg-1hJoeik6jBDNuYUVN89t-o8yo-aio], User-Agent=[NuGet Command Line/3.4.4.1321 (Microsoft Windows NT 6.2.9200.0)], Host=[localhost:48080], Accept-Encoding=[gzip, deflate], Content-Length=[142805], Content-Type=[multipart/form-data; boundary="b1e463fc-3952-4891-b631-87bb2beaacf4"]}]
21:18:18.621 10-02-2018 | DEBUG | qtp147623131-64      | o.springframework.web.filter.RequestContextFilter  | Bound request context to thread: SecurityContextHolderAwareRequestWrapper[ FirewalledRequest[ org.carlspring.strongbox.web.HeaderMappingFilter$ServletRequestDecorator@2f837f32]]
21:18:18.622 10-02-2018 | DEBUG | qtp147623131-64      | org.springframework.web.servlet.DispatcherServlet  | DispatcherServlet with name 'dispatcher' processing PUT request for [/storages/storage-nuget/nuget-releases/]
21:18:18.622 10-02-2018 | DEBUG | qtp147623131-64      | o.s.w.s.m.m.a.RequestMappingHandlerMapping         | Looking up handler method for path /storages/storage-nuget/nuget-releases/
21:18:18.623 10-02-2018 | DEBUG | qtp147623131-64      | o.s.w.s.m.m.a.RequestMappingHandlerMapping         | Returning handler method [public org.springframework.http.ResponseEntity org.carlspring.strongbox.controllers.nuget.NugetArtifactController.putPackage(java.lang.String,java.lang.String,java.lang.String,javax.servlet.http.HttpServletRequest)]
21:18:18.624 10-02-2018 | DEBUG | qtp147623131-64      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.carlspring.strongbox.security.vote.CustomAccessDecisionVoter@42919f5a, returned: 0
21:18:18.625 10-02-2018 | DEBUG | qtp147623131-64      | o.c.s.security.vote.MethodAccessDecisionManager    | Voter: org.carlspring.strongbox.security.vote.CustomPreInvocationAuthorizationAdviceVoter@19814548, returned: 1
21:18:18.626 10-02-2018 | INFO  | qtp147623131-64      | o.c.s.controllers.nuget.NugetArtifactController    | Nuget push request: storageId-[storage-nuget]; repositoryId-[nuget-releases]
142805
21:18:18.650 10-02-2018 | INFO  | qtp147623131-64      | o.c.s.controllers.nuget.NugetArtifactController    | NuGet package content length [142577]
21:18:18.683 10-02-2018 | INFO  | qtp147623131-64      | o.c.strongbox.services.ArtifactManagementService   | Validate artifact with path [C:\Users\Daniel\Desktop\strongbox-web-integration-tests\target\strongbox-vault\storages\storage-nuget\nuget-releases\Org.Carlspring.Swit.Tiwtd.Transitive\1.0.0\Org.Carlspring.Swit.Tiwtd.Transitive.1.0.0.nupkg]
21:18:18.687 10-02-2018 | INFO  | qtp147623131-64      | o.c.strongbox.services.ArtifactManagementService   | Validate artifact with coordinates [Org.Carlspring.Swit.Tiwtd.Transitive/1.0.0/Org.Carlspring.Swit.Tiwtd.Transitive.1.0.0.nupkg]
21:18:18.690 10-02-2018 | ERROR | qtp147623131-64      | o.c.s.controllers.nuget.NugetArtifactController    | Failed to process Nuget push request: storage-nuget:nuget-releases
org.carlspring.strongbox.storage.ArtifactStorageException: org.carlspring.strongbox.storage.validation.version.VersionValidationException: The storage-nuget:nuget-releases repository does not allow artifact re-deployment! (Org.Carlspring.Swit.Tiwtd.Transitive/1.0.0/Org.Carlspring.Swit.Tiwtd.Transitive.1.0.0.nupkg)
        at org.carlspring.strongbox.services.ArtifactManagementService.performRepositoryAcceptanceValidation(ArtifactManagementService.java:340)
        at org.carlspring.strongbox.services.ArtifactManagementService.validateAndStore(ArtifactManagementService.java:100)
        at org.carlspring.strongbox.services.ArtifactManagementService$$FastClassBySpringCGLIB$$b290f309.invoke(<generated>)
        at org.springframework.cglib.proxy
```

**Comment by carlspring** [comment]
@danielbrzn ,

I propose handling this in as a separate issue. Would you mind raising it as a new one?
Thanks!

**Comment by SoulSilence** [comment]
on. My sbt test before new PR cleared all strongbox that was deployed in target. And it could make harm for another tests. If nuget tests at this moment are ok I think that all's fine. At this moment they are fine for me on my machine.

**Comment by carlspring** [comment]
Okay, thanks for confirming!

...And thanks to everyone for helping! :)
