### ISSUE TITLE
Investigate the random test failures in the org.carlspring.strongbox.providers.layout.Maven2LayoutProviderTest

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#984]
The `org.carlspring.strongbox.providers.layout.Maven2LayoutProviderTest` is randomly failing in Jenkins under Ubuntu:

**Error Message for `org.carlspring.strongbox.providers.layout.Maven2LayoutProviderTest.testDeleteArtifact`**
```
Lock held by this virtual machine: /home/jenkins/workspace/jenkins-strongbox-strongbox-ubuntu-564-VCV86Jf/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage0/m2lp-releases/.index/local/write.lock
Stacktrace
org.carlspring.strongbox.repository.RepositoryInitializationException: Lock held by this virtual machine: /home/jenkins/workspace/jenkins-strongbox-strongbox-ubuntu-564-VCV86Jf/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage0/m2lp-releases/.index/local/write.lock
	at org.carlspring.strongbox.providers.layout.Maven2LayoutProviderTest.initialize(Maven2LayoutProviderTest.java:78)
Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by this virtual machine: /home/jenkins/workspace/jenkins-strongbox-strongbox-ubuntu-564-VCV86Jf/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage0/m2lp-releases/.index/local/write.lock
	at org.carlspring.strongbox.providers.layout.Maven2LayoutProviderTest.initialize(Maven2LayoutProviderTest.java:78)
```
**Error Message for `org.carlspring.strongbox.providers.layout.Maven2LayoutProviderTest.testDeleteArtifactDirectory`**
```
Error Message
/home/jenkins/workspace/jenkins-strongbox-strongbox-ubuntu-564-VCV86Jf/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage0/m2lp-releases/.index/local/_0.si
Stacktrace
org.carlspring.strongbox.repository.RepositoryInitializationException: /home/jenkins/workspace/jenkins-strongbox-strongbox-ubuntu-564-VCV86Jf/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage0/m2lp-releases/.index/local/_0.si
	at org.carlspring.strongbox.providers.layout.Maven2LayoutProviderTest.initialize(Maven2LayoutProviderTest.java:78)
Caused by: java.nio.file.NoSuchFileException: /home/jenkins/workspace/jenkins-strongbox-strongbox-ubuntu-564-VCV86Jf/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-maven-layout/strongbox-storage-maven-layout-provider/target/strongbox-vault/storages/storage0/m2lp-releases/.index/local/_0.si
	at org.carlspring.strongbox.providers.layout.Maven2LayoutProviderTest.initialize(Maven2LayoutProviderTest.java:78)
```

**Environment details:**
```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z)
Maven home: /java/mvn-3.5.4
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /java/jdk-1.8u191-b12/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.15.0-43-generic", arch: "amd64", family: "unix"
```

Please, feel free to [join our chat](https://chat.carlspring.org/channel/community), if you have any questions.

**Comment by carlspring** [comment]
@sbespalov : Is this now fixed by #986?

**Comment by sbespalov** [comment]
@carlspring I think it should be fixed.

**Comment by carlspring** [comment]
If it is, would you mind trying it out and re-enabling the test, please?

**Comment by sbespalov** [comment]
as I see it's already enabled in `master`
