### ISSUE TITLE
Investigate the random test failures in the org.carlspring.strongbox.controllers.layout.npm.NpmArtifactControllerTestIT

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#985]
This test is currently `@Disabled` and you will have to remove this annotation in order to execute it

This task is a sub-task of #948.

**Error Message for `org.carlspring.strongbox.controllers.layout.npm.NpmArtifactControllerTestIT`:**

```
Failed to resolve /storages/storage0/nactit-npm-group/compression/-/compression-1.7.2.tgz!
Stacktrace
org.opentest4j.AssertionFailedError: Failed to resolve /storages/storage0/nactit-npm-group/compression/-/compression-1.7.2.tgz!
	at org.carlspring.strongbox.controllers.layout.npm.NpmArtifactControllerTestIT.testResolveArtifactViaGroupWithProxy(NpmArtifactControllerTestIT.java:140)
Standard Output
22:03:17.867 13-01-2019 | INFO  | kJoinPool-1-worker-1 | o.c.s.users.userdetails.XmlUserDetailService       | Authorise under org.carlspring.strongbox.users.userdetails.StrongboxUserDetails@78940faa
22:03:17.871 13-01-2019 | INFO  | kJoinPool-1-worker-1 | o.c.s.resource.ConfigurationResourceResolver       | Try to fetch configuration resource path [/home/jenkins/workspace/jenkins-strongbox-strongbox-master-1967-ExTNYvF/strongbox-web-core/target/strongbox/etc/conf/strongbox-cron-tasks.xml]
22:03:17.871 13-01-2019 | INFO  | kJoinPool-1-worker-1 | o.c.s.resource.ConfigurationResourceResolver       | Using provided resource path [/home/jenkins/workspace/jenkins-strongbox-strongbox-master-1967-ExTNYvF/strongbox-web-core/target/strongbox/etc/conf/strongbox-cron-tasks.xml]
22:03:27.980 13-01-2019 | ERROR | kJoinPool-1-worker-1 | o.c.s.providers.repository.ProxyRepositoryProvider | Failed to resolve Path for proxied artifact [/home/jenkins/workspace/jenkins-strongbox-strongbox-master-1967-ExTNYvF/strongbox-web-core/target/strongbox-vault/storages/storage0/nactit-npm-proxy/compression/compression/1.7.2/compression-1.7.2.tgz]
java.io.IOException: Unreadable response for compression/-/compression-1.7.2.tgz. Response status is 409
	at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.getConnection(RemoteArtifactStreamFetcher.java:76)
	at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher.access$000(RemoteArtifactStreamFetcher.java:15)
	at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher$RemoteArtifactInputStream.getConnection(RemoteArtifactStreamFetcher.java:117)
	at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher$RemoteArtifactInputStream.getTarget(RemoteArtifactStreamFetcher.java:128)
	at org.carlspring.strongbox.providers.repository.proxied.RemoteArtifactStreamFetcher$RemoteArtifactInputStream.available(RemoteArtifactStreamFetcher.java:167)
	at java.io.FilterInputStream.available(FilterInputStream.java:168)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryInputStream.available(ProxyRepositoryInputStream.java:94)
	at java.io.BufferedInputStream.available(BufferedInputStream.java:410)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.doFetch(ProxyRepositoryArtifactResolver.java:88)
	at org.carlspring.strongbox.providers.repository.proxied.ProxyRepositoryArtifactResolver.fetchRemoteResource(ProxyRepositoryArtifactResolver.java:75)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.resolvePathExclusive(ProxyRepositoryProvider.java:101)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider.fetchPath(ProxyRepositoryProvider.java:73)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:219)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:43)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider$$FastClassBySpringCGLIB$$f2b828e0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at org.carlspring.strongbox.providers.repository.ProxyRepositoryProvider$$EnhancerBySpringCGLIB$$f8bf68a3.fetchPath(<generated>)
	at org.carlspring.strongbox.providers.repository.GroupRepositoryProvider.resolvePathFromGroupMemberOrTraverse(GroupRepositoryProvider.java:151)
	at org.carlspring.strongbox.providers.repository.GroupRepositoryProvider.resolvePathTraversal(GroupRepositoryProvider.java:117)
	at org.carlspring.strongbox.providers.repository.GroupRepositoryProvider.fetchPath(GroupRepositoryProvider.java:92)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:219)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider.fetchPath(AbstractRepositoryProvider.java:43)
	at org.carlspring.strongbox.providers.io.AbstractRepositoryProvider$$FastClassBySpringCGLIB$$f2b828e0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at org.carlspring.strongbox.providers.repository.GroupRepositoryProvider$$EnhancerBySpringCGLIB$$69c790b6.fetchPath(<generated>)
	at org.carlspring.strongbox.services.impl.ArtifactResolutionServiceImpl.resolvePath(ArtifactResolutionServiceImpl.java:98)
	at org.carlspring.strongbox.controllers.layout.npm.NpmArtifactController.downloadPackage(NpmArtifactController.java:361)
	at org.carlspring.strongbox.controllers.layout.npm.NpmArtifactController$$FastClassBySpringCGLIB$$dee86fa2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at org.carlspring.strongbox.controllers.layout.npm.NpmArtifactController$$EnhancerBySpringCGLIB$$8351f4c4.downloadPackage(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:166)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.carlspring.strongbox.security.authentication.StrongboxAuthenticationFilter.doFilterInternal(StrongboxAuthenticationFilter.java:63)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.carlspring.strongbox.security.authentication.CustomAnonymousAuthenticationFilter.doFilter(CustomAnonymousAuthenticationFilter.java:43)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:133)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:165)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.performRequest(MockMvcRequestSenderImpl.java:194)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.sendRequest(MockMvcRequestSenderImpl.java:430)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.get(MockMvcRequestSenderImpl.java:608)
	at io.restassured.module.mockmvc.internal.MockMvcRequestSenderImpl.get(MockMvcRequestSenderImpl.java:76)
	at org.carlspring.strongbox.rest.client.RestAssuredArtifactClient.getArtifactAsByteArray(RestAssuredArtifactClient.java:197)
	at org.carlspring.strongbox.rest.client.RestAssuredArtifactClient.getResource(RestAssuredArtifactClient.java:162)
	at org.carlspring.strongbox.rest.client.RestAssuredArtifactClient.getResource(RestAssuredArtifactClient.java:149)
	at org.carlspring.strongbox.rest.common.NpmRestAssuredBaseTest.resolveArtifact(NpmRestAssuredBaseTest.java:124)
	at org.carlspring.strongbox.controllers.layout.npm.NpmArtifactControllerTestIT.testResolveArtifactViaGroupWithProxy(NpmArtifactControllerTestIT.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:131)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:169)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:139)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:119)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:169)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:139)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:119)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:169)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
22:03:27.981 13-01-2019 | ERROR | kJoinPool-1-worker-1 | o.c.s.providers.repository.GroupRepositoryProvider | Failed to resolve path [/home/jenkins/workspace/jenkins-strongbox-strongbox-master-1967-ExTNYvF/strongbox-web-core/target/strongbox-vault/storages/storage0/nactit-npm-proxy/compression/compression/1.7.2/compression-1.7.2.tgz]
22:03:27.982 13-01-2019 | WARN  | kJoinPool-1-worker-1 | o.c.s.rest.client.RestAssuredArtifactClient        | [getArtifactAsByteArray] response 404
```

**Comment by adavid9** [comment]
@carlspring This test is fixed, isn't it? I went into this test and ran it without any errors few times. Also there is no @Disabled annotation as you mentioned above, so probably someone already fixed this issue.

**Comment by carlspring** [comment]
@adavid9 ,

You'll have to run this off the `SB-1323` branch, I believe.

At the moment, the class on the `master` has the `@IntegrationTest` annotation and that's got `@Execution(ExecutionMode.SAME_THREAD)`. This should actually be `@Execution(ExecutionMode.CONCURRENT)` (either on this test, ot in the `@IntegrationTest`, which is what I believe was on the `SB-1323` branch).

The problem appears when executing the tests in parallel.

**Comment by carlspring** [comment]
@ptirador : This is probably now obsolete. Please, feel freel to close it, if you think it's working fine now.

Thanks! :)

**Comment by ptirador** [comment]
@carlspring: Currently this test class is working fine, without any random failure.
I proceed to close it.

**Comment by carlspring** [comment]
Thank you!
